### ISSUE TITLE
Umbrella issue for docs migration

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#10]
#### Summary

Todo:

- [x] Add issue + pr templates https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/5- 
- [x] Add CONTRIBUTING.md https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/7
- [x] Remove docs and tooling from old repos https://github.com/TheThingsNetwork/lorawan-stack/pull/3297 https://github.com/TheThingsIndustries/lorawan-stack/pull/2368
- [x] Host new docs repo (presumably tti.com/docs)
- [x] Redirect tti.com/docs
- [x] Add git hooks
- [x] Find a way to connect version tag to lw-stack repo - https://github.com/TheThingsIndustries/lorawan-stack-docs
- [x] Find a way to get API from tti lw-stack - https://github.com/TheThingsIndustries/lorawan-stack-docs
- [x] Generate API yamls - https://github.com/TheThingsIndustries/lorawan-stack-docs
- doc/data/api/tti.lorawan.v3/services.yml (generated by tools/mage/proto.go and tools/mage/proto.tti.go)
- doc/data/api/ttn.lorawan.v3/enums.yml (generated by tools/mage/proto.go and tools/mage/proto.tti.go)
- doc/data/api/ttn.lorawan.v3/services.yml (generated by tools/mage/proto.go and tools/mage/proto.tti.go)
- doc/data/events.json (generated by tools/generate_event_data.go)
